services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    command: sh -c "php artisan migrate && service nginx start && php-fpm"