services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:random_generated_key
    ports:
      - "9000:9000" # Exponiendo el puerto de PHP-FPM

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    depends_on:
      - app
    volumes:
      - .:/var/www/html
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80" # Nginx escucha en el puerto 8000
