services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    working_dir: /var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:your-app-key
    ports:
      - "9000:9000" # PHP-FPM escucha en este puerto

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    depends_on:
      - app
    volumes:
      - .:/var/www/html
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" # Nginx escucha en este puerto
